replicaCount: 1

image:
  repository: llm-cpu
  tag: latest
  pullPolicy: IfNotPresent # Important for local dev so it uses the image you built

# -- the options ---
hardware: cpu

# --- MODEL STORAGE ---
# Path inside the container
containerModelPath: /app/models
# Change this to the actual path on your host machin
hostModelPath: /data/models

service:
  type: ClusterIP
  port: 8000